swagger: '2.0'
definitions:
  Error:
    title: Error
    description: An error with code and message
    type: object
    properties:
      code:
        type: string
        description: Error code
      message:
        type: string
        description: Error message
